apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-app-config
  namespace: gitops-app
  labels:
    app.kubernetes.io/name: gitops-app
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
